apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /registry 
    server: 10.197.202.192 
  persistentVolumeReclaimPolicy: Recycle
